//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Inventario_KM.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Productos
    {
        public int intBitacoraID { get; set; }
        public Nullable<int> intProductoID { get; set; }
        public Nullable<System.DateTime> datFechaBitacora { get; set; }
        public Nullable<int> intTipoPrendaID { get; set; }
        public Nullable<int> intTallaID { get; set; }
        public Nullable<int> intColorID { get; set; }
        public string vchSKUProducto { get; set; }
        public string vchNombreProducto { get; set; }
        public Nullable<decimal> decCostoProducto { get; set; }
        public Nullable<int> intStockProducto { get; set; }
        public string vchDescripcionProducto { get; set; }
        public string vchImagenProducto { get; set; }
        public Nullable<bool> bitEstadoProducto { get; set; }
        public Nullable<System.DateTime> datFechaAltaProducto { get; set; }
        public Nullable<int> intEventoID { get; set; }
        public Nullable<int> intUsuarioAltaProducto { get; set; }
    
        public virtual CAT_Eventos CAT_Eventos { get; set; }
        public virtual CAT_Productos CAT_Productos { get; set; }
    }
}
