//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Inventario_KM.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_RolUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_RolUsuario()
        {
            this.CAT_Usuarios = new HashSet<CAT_Usuarios>();
        }
    
        public int intRolID { get; set; }
        public string vchNombreRol { get; set; }
        public string vchDescripcionRol { get; set; }
        public Nullable<bool> bitEstadoRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Usuarios> CAT_Usuarios { get; set; }
    }
}
