//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Inventario_KM.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Productos()
        {
            this.DetalleInvSal = new HashSet<DetalleInvSal>();
            this.DetalleInvEnt = new HashSet<DetalleInvEnt>();
            this.Bitacora_Productos = new HashSet<Bitacora_Productos>();
        }
    
        public int intProductoID { get; set; }
        public Nullable<int> intTipoPrendaID { get; set; }
        public Nullable<int> intTallaID { get; set; }
        public Nullable<int> intColorID { get; set; }
        public string vchSKUProducto { get; set; }
        public string vchNombreProducto { get; set; }
        public Nullable<decimal> decCostoProducto { get; set; }
        public Nullable<int> intStockProducto { get; set; }
        public string vchDescripcionProducto { get; set; }
        public string vchImagenProducto { get; set; }
        public Nullable<bool> bitEstadoProducto { get; set; }
        public Nullable<System.DateTime> datFechaAltaProducto { get; set; }
        public Nullable<int> intUsuarioAltaProducto { get; set; }
    
        public virtual CAT_Colores CAT_Colores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInvSal> DetalleInvSal { get; set; }
        public virtual CAT_Tallas CAT_Tallas { get; set; }
        public virtual CAT_TipoPrendas CAT_TipoPrendas { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInvEnt> DetalleInvEnt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora_Productos> Bitacora_Productos { get; set; }
    }
}
