//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Inventario_KM.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioEntrante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioEntrante()
        {
            this.DetalleInvEnt = new HashSet<DetalleInvEnt>();
        }
    
        public int intInventarioEntID { get; set; }
        public Nullable<int> intPersonaID { get; set; }
        public Nullable<int> intUsuarioID { get; set; }
        public Nullable<System.DateTime> datFechaInvEnt { get; set; }
        public Nullable<decimal> decTotalInvEnt { get; set; }
        public string vchEstadoInvEnt { get; set; }
    
        public virtual CAT_Personas CAT_Personas { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInvEnt> DetalleInvEnt { get; set; }
    }
}
